### PR TITLE
WIP resolve abstract class issues

### PR DESCRIPTION
**Pull request by ceteri**
Hi Carlos,

`MotiFiesta` looks great! I have a question, and also have this PR as a work in progress to try to resolve issues during build:

When running the `python3 utils/build_data.py` step, there's a dependency for `PyG` which wasn't specified in the `requirements.txt` so I've added that. However, I'm curious about which version of `PyG` was used in the development of this library?

When I try to run, the local `SyntheticMotifs` subclasses from `pyg.Dataset` which has abstract methods. The code shows impl of `__getitem__()` although the current `torch-geometric==2.3.1` would need impl of `__get__()` instead.

Should I be using a different version of `PyG` instead?

```
(venv) (base) derwen:~/src/MotiFiesta$ python3 utils/build_data.py
['/Users/paco/src/MotiFiesta/utils', '/Users/cgonzalez/Projects', '/Users/paco/src/MotiFiesta', '/Library/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload', '/Users/paco/src/MotiFiesta/venv/lib/python3.9/site-packages', '/Users/cgonzalez/Projects']
Downloading https://www.chrsmrrs.com/graphkerneldatasets/PROTEINS.zip
Extracting data/PROTEINS/PROTEINS.zip
Processing...
Done!
Downloading https://www.chrsmrrs.com/graphkerneldatasets/ENZYMES.zip
Extracting data/ENZYMES/ENZYMES.zip
Processing...
Done!
Downloading https://www.chrsmrrs.com/graphkerneldatasets/IMDB-BINARY.zip
Extracting data/IMDB-BINARY/IMDB-BINARY.zip
Processing...
Done!
Downloading https://www.chrsmrrs.com/graphkerneldatasets/COX2.zip
Extracting data/COX2/COX2.zip
Processing...
Done!
>>> MOTIF TYPE
Traceback (most recent call last):
  File "/Users/paco/src/MotiFiesta/utils/build_data.py", line 40, in <module>
    SyntheticMotifs(root='data', name=f'synth-distort-{m_type}-d{d:.2f}', seed=42, motif_size=10, motif_type=m_type, parent_size=20, distort_p=d)
TypeError: Can't instantiate abstract class SyntheticMotifs with abstract methods get, len
```

### CODE REVIEW

**Comment by ceteri** [comment]
When running the `python3 utils/build_data.py` step, there's a dependency for `PyG` which wasn't specified in the `requirements.txt` so I've added that. However, I'm curious about which version of `PyG` was used in the development of this library?

When I try to run, the local `SyntheticMotifs` subclasses from `pyg.Dataset` which has abstract methods. The code shows impl of `__getitem__()` although the current `torch-geometric==2.3.1` would need impl of `__get__()` instead.

**Comment by ceteri** [comment]
By pinning `torch-geometric == 2.2.0` (i.e., before abstract base classes were introduced to `pyg.data`) the `build_data.py` step gets further.

However, now there's another issue with:
```
ModuleNotFoundError: No module named 'torch_sparse'
```

After including `torch_sparse` in the requirements, the `pip` install fails on building a wheel.

So I'm guessing this repo was built on a particular platform (Linux?) with GPUs, and that `torch` was configured specifically for it?

**Comment by cgoliver** [comment]
Hi @ceteri thanks for the PR! Indeed I should have included versions in the requirements.txt. I will get to the computer I used to run the experiments this evening and get back to you tomorrow. The older versions of torch_geometric required manual installation of torch_sparse and torch_scatter.

**Comment by cgoliver** [comment]
Hey @ceteri so sorry for the delay! A conference got in the way of things. I just made a fairly major upgrade to the master branch which should make things much easier to run.

The requirements are all automatically installed with the latest package versions since I made the code pip installable. Check the README.

I haven't tested extensively but a small training job and data generation worked. Let me know if this fixes the current issue for you as well.

**Comment by ceteri** [comment]
Many thanks @cgoliver !

I can get through the issues mentioned before, at least through the `build_data_motifiesta` step, although there are a few minor issues and questions:

  * Does the dependency for `torch-geometric` need to be added to `requirements.txt` ?
  * Where is the file `models.tar.gz` located, which is mentioned in the README ?

Also, the file `MotiFiesta/utils/__pycache__/synthetic.cpython-39.pyc` is committed in the repo, although it get generated as part of the build.  Should that be removed from the repo (i.e., added to `.gitignore`) instead?

**Comment by cgoliver** [comment]
Thanks for checking that @ceteri , the issues should now be resolved in the latest master branch.

The `models.tar.gz` is now downloadable from a link in the readme.

**Comment by ceteri** [comment]
Thank you very much @cgoliver 
I'm getting much further on the build :)

Just made a fork where the `main` branch can be rebased to keep in sync with your repo, while the `init_build_train` shows what we're doing to install, build, and train:

  - https://github.com/ceteri/MotiFiesta/tree/init_build_train
  - https://github.com/ceteri/MotiFiesta/issues/1

I'm working on both macOS laptops (CPU only) and an Ubuntu laptop (GeForce RTX).
So far, I've got the macOS side running into training a model, but it hits an error on `scikit-learn` data dimensions. I'll keep debugging there.

On the Ubuntu side, I can get partway through the build, but I need to align the CUDA versions used in installation.  Will post those notes later today.

**Pull request closed without merging**
